### ISSUE TITLE
Link Parent and Funded Person

### ISSUE THREAD

**Issue by lcreid** [weenhanceit/autism-funding#10]
Implement the model for the many-to-many relationship between Parent and Funded Person. I believe that exactly one parent is considered the person who administers the funds, so the model representing the relationship has at least an attribute for whether this parent is the one the Ministry talks to.

**Comment by philcarrillo** [comment]
I am closing this issue as we have decided to go with a simple data model that stores user data that will be used to initialize forms.   This issue would resurface should we decided to upgrade the application to utilize a more general data model where we have separate tables for entities / address / phone number.
