### ISSUE TITLE
Static Pages

### ISSUE THREAD

**Issue by lcreid** [weenhanceit/autism-funding#14]
There are a number of 'static' pages providing content that is not based on data or what the user is doing.  Pages may be 'public' ( accessible to any user with the correct URL) or 'protected' (only accessable to users who have logged into the application).

Static pages include:
- **Home Page** _(Public)_ - static landing page that is the home page for unsigned in users.   This page briefly describes the application and invites users to either sign up or contact us.
- **Other Resources** _(Public)_ - A list of links to other sites with information that may be of interest to parents of autistic children
- **Contact Us** _(Public)_ - A page that documents how to contact us, why users should contact us and encourage requests for more functionality.
- **Help** _(Protected)_ - Brief description of the functionality of the app, instructions and dealing with errors and problems.

**Comment by philcarrillo** [comment]
Static pages have been implemented and reviewed.  Separate issues have been created for any bugs found on static pages
