### ISSUE TITLE
Proposed Methods for User 'State'

### ISSUE THREAD

**Issue by philcarrillo** [weenhanceit/autism-funding#31]
**The Issue**
The user experience depends on a number of factors - the most obvious being whether or not the user is a resident of BC.    Depending on what data the user has entered, the user will see different menus and will be re-directed to specific pages to encourage the user to enter missing information.
It is proposed that testing for the various conditions of user data is best encapsulated in a set of methods in the User model.

**Proposed Methods**
The following methods are proposed:
- _missing_key_info?_ - the method will return a true if the user has not entered the minimum information the application requires to provide basic functionality.   This method will return true of if there are no funded children defined, or if the province of the user address has not been defined.
- _bc_resident?_ - the method will return a true if the user has selected a province code (in their address) and the province code is BC.
- _can_create_new_rtp?_ - this method will return a true if the user is able to create a new RTP form.  Users can create new RTP forms if they are BC residents and have at least one funded child.
- _can_see_my_home?_ - this method will return a true, unless the user must be re-directed from My Home to My Profile.  Users are redirected if any of the following is true:
  - User has not entered a province as part of their address information
  - User has not defined any funded children
  - User has selected a province that is not BC, user has defined at least one funded child but the user has not created any invoices or RTP

**Actions**
The methods above are used by the controllers to determine the menus items seen by the user and which pages may be rendered without redirection.

On every page render, the current users' _can_see_my_home?_ is checked.  Ifs this is true, My Home will  be included in the menu

Before rendering My Home, users will be redirected to My Profile unless _can_see_my_home?_ is true.

When rendering My Home, a notification will be included telling the users that since they are not residents of BC, they can no longer add or edit any RTPs, unless _can_create_new_rtp?_ is true.

When rendering My Profile, a notification will be included telling the user that they must at least enter a province and one funded child before they will see any functionality, if _missing_key_Info?_ is true.

When rendering My Profile a notification will be included telling the user that the functionality of the site is only available to residents of BC, unless _bc_resident?_ is true.

**Comment by lcreid** [comment]
This is going in the right direction. I was thinking about how I would write the code that would use these methods. Am I correct in assuming that these are methods for the User class?

**Comment by philcarrillo** [comment]
This functionality has been edited and reviewed.    Any problems or bugs with this functionality has been documented in separate issues.
