### ISSUE TITLE
Issues Matching Invoice to RTP

### ISSUE THREAD

**Issue by philcarrillo** [weenhanceit/autism-funding#36]
There were some issues uncovered in testing the web application in the area of matching Invoice to RTP.

These issues were not followed up or fully tested - they need further review.

(See Issue #37:) An invoice from a service provider was entered with the service provider name, a date range within the RTP and an invoice amount.  No match was match to the RTP.   Investigation showed that this was due to the fact that the RTP did have a radio box selection made for "Payment to be provided to", although the form appeared to be printable.

I believe (since this is within the matching criteria) that the cf0925 should include this field in its printable? check.

(See Issue #39:) Also, noted that once a RTP was selected to match an invoice - it was not possible to set it back to Out of Pocket.

(See Issue #38:) Another problem noted, but not followed up on - an Invoice was assigned to an RTP - but shows in the summary as out of pocket.

(See Issue #40:) Another question - if you can assign an Invoice to multiple RTPs from the same provider - how do you identify which one to assign?

**Comment by lcreid** [comment]
The individual issues have been closed, and we have reviewed and re-tested the entire matching and allocation area, so closing.
