### ISSUE TITLE
Warning Created on Navigation away from Log In page, when no changes made

### ISSUE THREAD

**Issue by philcarrillo** [weenhanceit/autism-funding#69]
This is not a serious issues because it will not likely ever be an actual problem.  If I navigate to the log in page, and then attempt to navigate away, there will be a warning advising me of unsaved changes - even though no change to the data has been made.  This may seem confusing to a user to just changed his/her mind.

I believe the problem may occur because I am using Chrome and the Log In fields are populated using auto-fill (causing the browser to 'think' the data has changed).   However, since no data is saved from this page, it is counter intuitive to be 'blocked' from navigating away after changing data.

**Comment by lcreid** [comment]
It's not too hard to exclude the log-in screen from the check. I'll do it.

**Comment by lcreid** [comment]
We need to validate this better. I thought it was fixed, but I saw some strange behaviour after the fix.

**Comment by lcreid** [comment]
I think this is fixed. I'll close and we can re-open it if needed.
