### ISSUE TITLE
Login and Sign Up

### ISSUE THREAD

**Issue by lcreid** [weenhanceit/autism-funding#7]
The site will contain public pages and protected pages.  Public pages can be seen by any user accessing the URL.  Protected pages may only be seen by users with a valid account who have successfully signed into the site.   Sign in requires a valid email address and a password.

We will use [Devise](https://github.com/plataformatec/devise) to implement login security.

Users may create accounts by supplying an email address and a password.   Accounts are not valid until the user has verified the email address.    The site will email new users at the provided email address, users click a link to verify the address and validate their account.  Users will be able to recover lost passwords by being sent an email.

The data model allows users to be designated as administrators - but there is not mechanism in the application to set users as administrators and there is no functionality unique to administrators.

**Comment by philcarrillo** [comment]
This issue has been modified to only include Phase 1 security.   Phase 1 security means that only users with a user account may be able to add/view/edit parent and funded person information.   Users may create accounts without email confirmation.  Users may modify the passwords on their account

**Comment by philcarrillo** [comment]
This issue has been closed as Devise was used to implement the V00.01.00 release, users may create accounts with no email confirmation
