### ISSUE TITLE
My Home, 2 Funded Children - if both collaspes and Click My Home, 1 expands

### ISSUE THREAD

**Issue by philcarrillo** [weenhanceit/autism-funding#70]

**Comment by lcreid** [comment]
Fixed, but there's a disturbing linkage between how the screen works and how the preferences get saved. I guess I shouldn't say disturbing...

When we changed to having at most one window open, I changed the way I saved the preferences, on the idea that it was more natural to have only one preference for the child that was open. But sometimes there's no child open, and I wasn't saving it. 

I could have kept the preferences the old way. That would have required more code in the open panel preference setter, but might be more open to change in the future.

What's done is done.
