### ISSUE TITLE
Funded Person Model

### ISSUE THREAD

**Issue by lcreid** [weenhanceit/autism-funding#8]
The funded person has a name and a birth date at the very least. The funding is based on the birth date, because the "funding year" goes from the month after the birth month, up to and including the month of the next birthday. For example, a child born April 1st who's six years old and not yet 18 years old gets $6,000 per year to spend starting May 1st, and going up to April 30th of the subsequent year. 

The attributes are:
- Whether the child is in care of the Ministry
- First, middle, and last name
- Birth date

**Comment by philcarrillo** [comment]
This issue is encompassed by the **Data Model for MVP** issue and thus this issue has been closed
